# Generated by Django 4.2.5 on 2023-12-07 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('retirada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retirada',
            name='status',
            field=models.CharField(choices=[('Retirada', 'Retirada'), ('Devolvida', 'Devolvida'), ('Atrasada', 'Atrasada')], default='Retirada', help_text='Estatus da retirada', max_length=20, verbose_name='estatus'),
        ),
        migrations.AlterField(
            model_name='retirada',
            name='datadevolucao',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Data da devolução da chave', verbose_name='data_devolucao'),
        ),
        migrations.AlterField(
            model_name='retirada',
            name='dataretirada',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Data da retirada chave', verbose_name='data_retirada'),
        ),
    ]
