# Generated by Django 4.2.5 on 2023-12-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(help_text='Identificação da sala', max_length=50, unique=True, verbose_name='Identificação')),
                ('tipo', models.CharField(choices=[('Exclusiva', 'Exclusiva'), ('Comunitária', 'Comunitária')], default='Comunitária', max_length=50, verbose_name='Tipo da sala')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
    ]
