# Generated by Django 4.2.5 on 2023-12-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='disponibilidade',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Ocupada', 'Ocupada')], default='Disponível', max_length=10, verbose_name='Disnibilidade da sala'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='tipo',
            field=models.CharField(choices=[('Exclusiva', 'Exclusiva'), ('Comunitária', 'Comunitária')], default='Comunitária', max_length=11, verbose_name='Tipo da sala'),
        ),
    ]
