# Generated by Django 4.2.5 on 2023-12-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(help_text='Nome do funcionário', max_length=50, verbose_name='Nome'),
        ),
    ]
