# Generated by Django 4.2.5 on 2023-12-07 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0003_remove_sala_disponibilidade'),
        ('chave', '0002_alter_chave_options_chave_disponibilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='chave',
            name='sala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sala', to='sala.sala', verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='chave',
            name='disponibilidade',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Ocupada', 'Ocupada')], default='Disponível', max_length=10, verbose_name='Disponibilidade da sala'),
        ),
    ]
