# Generated by Django 4.2.5 on 2023-12-07 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0003_remove_sala_disponibilidade'),
        ('chave', '0003_chave_sala_alter_chave_disponibilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chave',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sala', to='sala.sala', verbose_name='Sala'),
        ),
    ]
