# Generated by Django 4.2.5 on 2023-12-07 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0003_remove_sala_disponibilidade'),
        ('chave', '0004_alter_chave_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chave',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sala.sala', verbose_name='Sala'),
        ),
    ]
